# Generated by Django 5.2.6 on 2025-09-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
